const dnd = {
  races: [
    {
      race: "Dragonborn",
      racial: [
        "+2 strength",
        "+1 charisma",
        "Draconic ancestry",
        "Breath Weapon",
        "Damage Resitance",
      ],
      description:
        "Dragonborn look very much like dragons standing erect in humanoid form, though they lack wings or a tail. The first dragonborn had scales of vibrant hues matching the colors of their dragon kin, but generations of interbreeding have created a more uniform appearance.",
      age: "Young dragonborn grow quickly. They walk hours after hatching, attain the size and development of a 10-year-old human child by the age of 3, and reach adulthood by 15. They live to be around 80.",
      size: "Dragonborn are taller and heavier than humans, standing well over 6 feet tall and averaging almost 250 pounds. Your size is Medium.",
      speed: "30 feet",
      languages: ["Commun", "Draconic"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/340/420/618/636272677995471928.png",
    },
    {
      race: "Dwarf",
      racial: [
        "+2 constitution",
        "Darkvision",
        "Dwarven Resilience",
        "Dwarven Combat Training",
        "Stonencunning",
      ],
      description:
        "Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal. Though they stand well under 5 feet tall, dwarves are so broad and compact that they can weigh as much as a human standing nearly two feet taller. Their courage and endurance are also easily a match for any of the larger folk.",
      age: "Dwarves mature at the same rate as humans, but they’re considered young until they reach the age of 50. On average, they live about 350 years.",
      size: "Dwarves stand between 4 and 5 feet tall and average about 150 pounds. Your size is Medium.",
      speed: "25 feet",
      languages: ["Commun", "Dwarvish"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/254/420/618/636271781394265550.png",
    },
    {
      race: "Elf",
      racial: [
        "+2 Dexterity",
        "Darkvision",
        "Keen Senses",
        "Fey Ancestry",
        "Trance",
      ],
      description:
        "Elves can live well over 700 years, giving them a broad perspective on events that might trouble the shorter-lived races more deeply. They are more often amused than excited, and more likely to be curious than greedy.",
      age: "Although elves reach physical maturity at about the same age as humans, the elven understanding of adulthood goes beyond physical growth to encompass worldly experience. An elf typically claims adulthood and an adult name around the age of 100 and can live to be 750 years old.",
      size: "Elves range from under 5 to over 6 feet tall and have slender builds. Your size is Medium.",
      speed: "30 feet",
      languages: ["Commun", "Elvish"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/7/639/420/618/636287075350739045.png",
    },
    {
      race: "Gnome",
      racial: ["+2 Intelligence", "Darkvision", "Gnome cunning"],
      description:
        "A gnome’s energy and enthusiasm for living shines through every inch of his or her tiny body. Gnomes average slightly over 3 feet tall and weigh 40 to 45 pounds. ",
      age: "Gnomes mature at the same rate humans do, and most are expected to settle down into an adult life by around age 40. They can live 350 to almost 500 years.",
      size: "Gnomes are between 3 and 4 feet tall and average about 40 pounds. Your size is Small.",
      speed: "25 feet",
      languages: ["Commun", "Gnomish, Undercommon"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/334/420/618/636272671553055253.png",
    },
    {
      race: "Half-elf",
      racial: [
        "+2 Charisma",
        "+1 to two other ability scores",
        "Darkvision",
        "Fey Ancestry",
        "Skill versatility",
      ],
      description:
        "To humans, half-elves look like elves, and to elves, they look human. In height, they’re on par with both parents, though they’re neither as slender as elves nor as broad as humans.",
      age: "Half-elves mature at the same rate humans do and reach adulthood around the age of 20. They live much longer than humans, however, often exceeding 180 years.",
      size: "Half-elves are about the same size as humans, ranging from 5 to 6 feet tall. Your size is Medium.",
      speed: "30 feet",
      languages: ["Commun", "Elvish, One extra language of your choice"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/481/420/618/636274618102950794.png",
    },
    {
      race: "Halfling",
      racial: ["+2 Dexterity", "Lucky", "Brave", "Halfling", "Nimbleness"],
      description:
        "The diminutive halflings survive in a world full of larger creatures by avoiding notice or, barring that, avoiding offense. Standing about 3 feet tall, they appear relatively harmless and so have managed to survive for centuries in the shadow of empires and on the edges of wars and political strife. They are inclined to be stout, weighing between 40 and 45 pounds.",
      age: "A halfling reaches adulthood at the age of 20 and generally lives into the middle of his or her second century.",
      size: "Halflings average about 3 feet tall and weigh about 40 pounds. Your size is Small.",
      speed: "25 feet",
      languages: ["Commun", "Halfling"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/256/420/618/636271789409776659.png",
    },
    {
      race: "Half-Orc",
      racial: [
        "+2 Strength",
        "+1 Constitution",
        "Darkvision",
        "Menacing",
        "Relentless",
        "Endurance",
        "Savage Attacks",
      ],
      description:
        "Half-orcs exhibit a blend of orcish and human characteristics, and their appearance varies widely. Grayish skin tones and prominent teeth are the most common shared elements among these folk.",
      age: "Half-orcs mature a little faster than humans, reaching adulthood around age 14. They age noticeably faster and rarely live longer than 75 years.",
      size: "Half-orcs are somewhat larger and bulkier than humans, and they range from 5 to well over 6 feet tall. Your size is Medium.",
      speed: "30 feet",
      languages: ["Commun", "Orc"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/466/420/618/636274570630462055.png",
    },
    {
      race: "Human",
      racial: ["+1 to All Ability Scores", "Extra language"],
      description:
        "Humans are the most adaptable and ambitious people among the common races. They have widely varying tastes, morals, and customs in the many different lands where they have settled.",
      age: "Humans reach adulthood in their late teens and live less than a century.",
      size: "Humans vary widely in height and build, from barely 5 feet to well over 6 feet tall. Regardless of your position in that range, your size is Medium.",
      speed: "30 feet",
      languages: ["Commun", "Extra language you choice"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/258/420/618/636271801914013762.png",
    },
    {
      race: "Tiefling",
      racial: [
        "+2 Charisma",
        "+1 Intelligence",
        "Darkvision",
        "Hellish Resistance",
        "Infernal Legacy",
      ],
      description:
        "To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye: this is the lot of the tiefling.",
      age: "Tieflings mature at the same rate as humans but live a few years longer.",
      size: "Tieflings are about the same size and build as humans. Your size is Medium.",
      speed: "30 feet",
      languages: ["Commun", "Infernal"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/7/641/420/618/636287076637981942.png",
    },
  ],
  classes: [
    {
      class: "Barbarian",
      hits: "d12",
      primary_ability: "Strength",
      saving_throw: "Strength & constitution",
      armor_weapons:
        ["Light and medium armor", "shields", "simple and martial weapons"],
      img: "https://www.dndbeyond.com/attachments/thumbnails/0/679/400/417/c3barbarianintro.png",
    },
    {
      class: "Bard",
      hits: "d8",
      primary_ability: "Charisma",
      saving_throw: "Dexterity & Charisma",
      armor_weapons:
        ["Light armor", "simple weapons", "hand crossbows", "longswords", "rapiers", "shortswords"],
      img: "https://www.dndbeyond.com/attachments/thumbnails/0/684/400/406/c3bardintro.png",
    },
    {
      class: "Cleric",
      hits: "d8",
      primary_ability: "Wisdom",
      saving_throw: "Wisdom & Charisma",
      armor_weapons: ["Light and medium armor", "shields", "simple weapons"],
      img: "https://www.dndbeyond.com/attachments/thumbnails/0/684/400/406/c3bardintro.png",
    },
    {
      class: "Druid",
      hits: "d8",
      primary_ability: "Wisdom",
      saving_throw: "Wisdom & Intelligence",
      armor_weapons: ["Light armor", "shields (Druids will not wear armor or use shields made of metal)", "medium armor"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/346/420/618/636272691461725405.png",
    },
    {
      class: "Fighter",
      hits: "d10",
      primary_ability: "Strength or Dexterity",
      saving_throw: "Strength & Constitution",
      armor_weapons: ["All armor", "Shields"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/359/420/618/636272697874197438.png",
    },
    {
      class: "Monk",
      hits: "d8",
      primary_ability: "Widsom & Dexterity",
      saving_throw: "Strength & Dexterity",
      armor_weapons: ["None"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/489/420/618/636274646181411106.png",
    },
    {
      class: "Paladin",
      hits: "d10",
      primary_ability: "Strength & Charisma",
      saving_throw: "Widsom & Charisma",
      armor_weapons: ["All armors", "Shields"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/365/420/618/636272701937419552.png",
    },
    {
      class: "Ranger",
      hits: "d10",
      primary_ability: "Dexterity & Widsom",
      saving_throw: "Strength & Dexterity",
      armor_weapons: ["Light armors", "Medium armors", "shields"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/367/420/618/636272702826438096.png",
    },
    {
      class: "Rogue",
      hits: "d8",
      primary_ability: "Dexterity",
      saving_throw: "Intelligence & Dexterity",
      armor_weapons: ["Light armors"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/384/420/618/636272820319276620.png",
    },
    {
      class: "Sorcerer",
      hits: "d6",
      primary_ability: "Charisma",
      saving_throw: "Constitution & Charisma",
      armor_weapons: ["None"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/485/420/618/636274643818663058.png",
    },
    {
      class: "Warlock",
      hits: "d8",
      primary_ability: "Charisma",
      saving_throw: "Widsom & Charisma",
      armor_weapons: ["Light armor"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/375/420/618/636272708661726603.png",
    },
    {
      class: "Wizard",
      hits: "d6",
      primary_ability: "Intelligence",
      saving_throw: "Widsom & Intelligence",
      armor_weapons: ["None"],
      img: "https://www.dndbeyond.com/avatars/thumbnails/6/357/420/618/636272696881281556.png",
    },
  ],
};

module.exports = dnd;
